sudo: required

language: c

services:
  - docker

before_install:
  - make -C meta docker-image
  - make -C tools/taish docker-image

script:
  - make -C meta docker
  - make -C meta test
  - make test
  - cp ./stub/libtai.so ./tools/taish/
  - make -C tools/taish docker
