name: publish

on:
    push:
        branches:
        - master
jobs:
    job:
        runs-on: ubuntu-latest
        steps:
        - uses: crazy-max/ghaction-docker-buildx@v1
          with:
              version: latest
        - uses: actions/checkout@v2
        - run: |
            import os
            ref = os.environ['GITHUB_REF']
            branch = ref[11:]
            with open(os.environ['GITHUB_ENV'], "a") as f:
                tag = "latest" if branch == "master" else branch
                f.write(f"DOCKER_IMAGE_TAG={tag}\n")
          shell: python
        - run: make builder
        - run: make image
        - run: docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        - run: docker tag tai docker.pkg.github.com/telecominfraproject/oopt-tai/tai:${{ env.DOCKER_IMAGE_TAG }}
        - name: Publish Docker image to Github Package
          run: docker push docker.pkg.github.com/telecominfraproject/oopt-tai/tai:${{ env.DOCKER_IMAGE_TAG }}
        - run: docker tag tai docker.io/microsonic/tai:${{ env.DOCKER_IMAGE_TAG }}
        - name: Publish Docker image to Docker Hub
          uses: ./.github/actions/publish-docker-image
          with:
              name: microsonic/tai
              username: ${{ secrets.DOCKER_USER }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              tags: ${{ env.DOCKER_IMAGE_TAG }}
